version: '3'
services:
  stock-valor:
    image: stock-valor
    container_name: stock-valor
    restart: always
    build:
      context: ./
      dockerfile: docker/Dockerfile
    environment:
      - VIRTUAL_HOST=localhost
      - LETSENCRYPT_HOST=localhost
      - LETSENCRYPT_EMAIL=malf88@gmail.com
    volumes:
      - ./:/var/www/
    ports:
      - 82:80
    expose:
      - 82

networks:
  default:
    external:
      name: webproxy